/**
 * Created by Quake on 07.11.2017.
 */
module.exports.getInstance = function (
    randomSeed,
    tickCount,
    worldWidth,
    worldHeight,
    fogOfWarEnabled,
    victoryScore,
    facilityCaptureScore,
    vehicleEliminationScore,
    actionDetectionInterval,
    baseActionCount,
    additionalActionCountPerControlCenter,
    maxUnitGroup,
    terrainWeatherMapColumnCount,
    terrainWeatherMapRowCount,
    plainTerrainVisionFactor,
    plainTerrainStealthFactor,
    plainTerrainSpeedFactor,
    swampTerrainVisionFactor,
    swampTerrainStealthFactor,
    swampTerrainSpeedFactor,
    forestTerrainVisionFactor,
    forestTerrainStealthFactor,
    forestTerrainSpeedFactor,
    clearWeatherVisionFactor,
    clearWeatherStealthFactor,
    clearWeatherSpeedFactor,
    cloudWeatherVisionFactor,
    cloudWeatherStealthFactor,
    cloudWeatherSpeedFactor,
    rainWeatherVisionFactor,
    rainWeatherStealthFactor,
    rainWeatherSpeedFactor,
    vehicleRadius,
    tankDurability,
    tankSpeed,
    tankVisionRange,
    tankGroundAttackRange,
    tankAerialAttackRange,
    tankGroundDamage,
    tankAerialDamage,
    tankGroundDefence,
    tankAerialDefence,
    tankAttackCooldownTicks,
    tankProductionCost,
    ifvDurability,
    ifvSpeed,
    ifvVisionRange,
    ifvGroundAttackRange,
    ifvAerialAttackRange,
    ifvGroundDamage,
    ifvAerialDamage,
    ifvGroundDefence,
    ifvAerialDefence,
    ifvAttackCooldownTicks,
    ifvProductionCost,
    arrvDurability,
    arrvSpeed,
    arrvVisionRange,
    arrvGroundDefence,
    arrvAerialDefence,
    arrvProductionCost,
    arrvRepairRange,
    arrvRepairSpeed,
    helicopterDurability,
    helicopterSpeed,
    helicopterVisionRange,
    helicopterGroundAttackRange,
    helicopterAerialAttackRange,
    helicopterGroundDamage,
    helicopterAerialDamage,
    helicopterGroundDefence,
    helicopterAerialDefence,
    helicopterAttackCooldownTicks,
    helicopterProductionCost,
    fighterDurability,
    fighterSpeed,
    fighterVisionRange,
    fighterGroundAttackRange,
    fighterAerialAttackRange,
    fighterGroundDamage,
    fighterAerialDamage,
    fighterGroundDefence,
    fighterAerialDefence,
    fighterAttackCooldownTicks,
    fighterProductionCost,
    maxFacilityCapturePoints,
    facilityCapturePointsPerVehiclePerTick,
    facilityWidth,
    facilityHeight
) {
    return {
        randomSeed: randomSeed,
        tickCount: tickCount,
        worldWidth: worldWidth,
        worldHeight: worldHeight,
        fogOfWarEnabled: fogOfWarEnabled,
        victoryScore: victoryScore,
        facilityCaptureScore: facilityCaptureScore,
        vehicleEliminationScore: vehicleEliminationScore,
        actionDetectionInterval: actionDetectionInterval,
        baseActionCount: baseActionCount,
        additionalActionCountPerControlCenter: additionalActionCountPerControlCenter,
        maxUnitGroup: maxUnitGroup,
        terrainWeatherMapColumnCount: terrainWeatherMapColumnCount,
        terrainWeatherMapRowCount: terrainWeatherMapRowCount,
        plainTerrainVisionFactor: plainTerrainVisionFactor,
        plainTerrainStealthFactor: plainTerrainStealthFactor,
        plainTerrainSpeedFactor: plainTerrainSpeedFactor,
        swampTerrainVisionFactor: swampTerrainVisionFactor,
        swampTerrainStealthFactor: swampTerrainStealthFactor,
        swampTerrainSpeedFactor: swampTerrainSpeedFactor,
        forestTerrainVisionFactor: forestTerrainVisionFactor,
        forestTerrainStealthFactor: forestTerrainStealthFactor,
        forestTerrainSpeedFactor: forestTerrainSpeedFactor,
        clearWeatherVisionFactor: clearWeatherVisionFactor,
        clearWeatherStealthFactor: clearWeatherStealthFactor,
        clearWeatherSpeedFactor: clearWeatherSpeedFactor,
        cloudWeatherVisionFactor: cloudWeatherVisionFactor,
        cloudWeatherStealthFactor: cloudWeatherStealthFactor,
        cloudWeatherSpeedFactor: cloudWeatherSpeedFactor,
        rainWeatherVisionFactor: rainWeatherVisionFactor,
        rainWeatherStealthFactor: rainWeatherStealthFactor,
        rainWeatherSpeedFactor: rainWeatherSpeedFactor,
        vehicleRadius: vehicleRadius,
        tankDurability: tankDurability,
        tankSpeed: tankSpeed,
        tankVisionRange: tankVisionRange,
        tankGroundAttackRange: tankGroundAttackRange,
        tankAerialAttackRange: tankAerialAttackRange,
        tankGroundDamage: tankGroundDamage,
        tankAerialDamage: tankAerialDamage,
        tankGroundDefence: tankGroundDefence,
        tankAerialDefence: tankAerialDefence,
        tankAttackCooldownTicks: tankAttackCooldownTicks,
        tankProductionCost: tankProductionCost,
        ifvDurability: ifvDurability,
        ifvSpeed: ifvSpeed,
        ifvVisionRange: ifvVisionRange,
        ifvGroundAttackRange: ifvGroundAttackRange,
        ifvAerialAttackRange: ifvAerialAttackRange,
        ifvGroundDamage: ifvGroundDamage,
        ifvAerialDamage: ifvAerialDamage,
        ifvGroundDefence: ifvGroundDefence,
        ifvAerialDefence: ifvAerialDefence,
        ifvAttackCooldownTicks: ifvAttackCooldownTicks,
        ifvProductionCost: ifvProductionCost,
        arrvDurability: arrvDurability,
        arrvSpeed: arrvSpeed,
        arrvVisionRange: arrvVisionRange,
        arrvGroundDefence: arrvGroundDefence,
        arrvAerialDefence: arrvAerialDefence,
        arrvProductionCost: arrvProductionCost,
        arrvRepairRange: arrvRepairRange,
        arrvRepairSpeed: arrvRepairSpeed,
        helicopterDurability: helicopterDurability,
        helicopterSpeed: helicopterSpeed,
        helicopterVisionRange: helicopterVisionRange,
        helicopterGroundAttackRange: helicopterGroundAttackRange,
        helicopterAerialAttackRange: helicopterAerialAttackRange,
        helicopterGroundDamage: helicopterGroundDamage,
        helicopterAerialDamage: helicopterAerialDamage,
        helicopterGroundDefence: helicopterGroundDefence,
        helicopterAerialDefence: helicopterAerialDefence,
        helicopterAttackCooldownTicks: helicopterAttackCooldownTicks,
        helicopterProductionCost: helicopterProductionCost,
        fighterDurability: fighterDurability,
        fighterSpeed: fighterSpeed,
        fighterVisionRange: fighterVisionRange,
        fighterGroundAttackRange: fighterGroundAttackRange,
        fighterAerialAttackRange: fighterAerialAttackRange,
        fighterGroundDamage: fighterGroundDamage,
        fighterAerialDamage: fighterAerialDamage,
        fighterGroundDefence: fighterGroundDefence,
        fighterAerialDefence: fighterAerialDefence,
        fighterAttackCooldownTicks: fighterAttackCooldownTicks,
        fighterProductionCost: fighterProductionCost,
        maxFacilityCapturePoints: maxFacilityCapturePoints,
        facilityCapturePointsPerVehiclePerTick: facilityCapturePointsPerVehiclePerTick,
        facilityWidth: facilityWidth,
        facilityHeight: facilityHeight
    };
};
